In [3]:
# 1.Create a 5x5 NumPy matrix with random integers from 0 to 9, then define a 3x3 filter (kernel)
# and manually perform a single convolution operation (no padding, stride 1) to produce the activation map.

import numpy as np

np.random.seed(10)
input_matrix = np.random.randint(0, 10, (5, 5))

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

region = input_matrix[0:3, 0:3]
value = np.sum(region * kernel)

activation_map = np.zeros((3, 3))

In [5]:
for i in range(3):
    for j in range(3):
        region = input_matrix[i:i+3, j:j+3]
        activation_map[i, j] = np.sum(region * kernel)

print("Input Matrix:")
print(input_matrix)

print("\nKernel:")
print(kernel)

print("\nActivation Map:")
print(activation_map)

Input Matrix:
[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:
[[ 5. -2.  3.]
 [-8.  0. 12.]
 [ 1.  3.  2.]]


In [8]:
# 2.Implement a Python function apply_stride_convolution(input_matrix, kernel, stride) that performs convolution with a given stride on a 6x6 matrix and a 3x3 kernel, returning the resulting activation map.<br><br><em><strong>Hint:</strong>
# Use nested loops to move the kernel by the stride value over the input matrix.</em>

import numpy as np

def apply_stride_convolution(input_matrix, kernel, stride):

    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = (input_rows - kernel_rows) // stride + 1
    output_cols = (input_cols - kernel_cols) // stride + 1

    output = np.zeros((output_rows, output_cols))

    for i in range(0, input_rows - kernel_rows + 1, stride):
        for j in range(0, input_cols - kernel_cols + 1, stride):

            region = input_matrix[i:i+kernel_rows, j:j+kernel_cols]

            output[i//stride, j//stride] = np.sum(region * kernel)

    return output


In [10]:
input_matrix = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 1, 2, 3],
    [4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 1, 2, 3],
    [4, 5, 6, 7, 8, 9]
])

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

stride = 2

result = apply_stride_convolution(input_matrix, kernel, stride)

print("Input Matrix:")
print(input_matrix)

print("\nKernel:")
print(kernel)

print("\nStride:", stride)

print("\nActivation Map:")
print(result)

Input Matrix:
[[1 2 3 4 5 6]
 [7 8 9 1 2 3]
 [4 5 6 7 8 9]
 [1 2 3 4 5 6]
 [7 8 9 1 2 3]
 [4 5 6 7 8 9]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Stride: 2

Activation Map:
[[-6.  3.]
 [-6.  3.]]


In [12]:
# 3.Modify your convolution code to add zero-padding of 1 around the input matrix before applying 
# the convolution, and show the new activation map output.

import numpy as np

np.random.seed(10)

input_matrix = np.random.randint(0, 10, (5, 5))

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

padded_matrix = np.pad(input_matrix, pad_width=1,
                       mode='constant', constant_values=0)

output = np.zeros((5, 5))


In [14]:
for i in range(5):
    for j in range(5):

        region = padded_matrix[i:i+3, j:j+3]

        output[i, j] = np.sum(region * kernel)

print("Original Matrix:")
print(input_matrix)

print("\nPadded Matrix:")
print(padded_matrix)

print("\nActivation Map with Padding:")
print(output)

Original Matrix:
[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]]

Padded Matrix:
[[0 0 0 0 0 0 0]
 [0 9 4 0 1 9 0]
 [0 0 1 8 9 0 0]
 [0 8 6 4 3 0 0]
 [0 4 6 8 1 8 0]
 [0 4 1 3 6 5 0]
 [0 0 0 0 0 0 0]]

Activation Map with Padding:
[[ -5.   1.  -5.  -1.  10.]
 [-11.   5.  -2.   3.  13.]
 [-13.  -8.   0.  12.  13.]
 [-13.   1.   3.   2.  10.]
 [ -7.  -3.   0.  -2.   7.]]


In [17]:
# 4.Visualize the effect of different filters by applying both an edge detection kernel and a blur kernel to the same 5x5 matrix and print both activation maps side by side.<br><br><em><strong>Hint:</strong> Use the Sobel
# or Laplacian kernel for edge detection and an averaging kernel for blur.</em>

import numpy as np

input_matrix = np.array([
    [10, 20, 30, 40, 50],
    [20, 30, 40, 50, 60],
    [30, 40, 50, 60, 70],
    [40, 50, 60, 70, 80],
    [50, 60, 70, 80, 90]
])

edge_kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

blur_kernel = np.ones((3, 3)) / 9


In [20]:
def convolution(input_matrix, kernel):

    rows, cols = input_matrix.shape
    k_rows, k_cols = kernel.shape

    output = np.zeros((
        rows - k_rows + 1,
        cols - k_cols + 1
    ))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):

            region = input_matrix[
                i:i+k_rows,
                j:j+k_cols
            ]

            output[i, j] = np.sum(region * kernel)

    return output


In [22]:
edge_output = convolution(input_matrix, edge_kernel)
blur_output = convolution(input_matrix, blur_kernel)

print("Input Matrix:")
print(input_matrix)

print("\nEdge Detection Activation Map:")
print(edge_output)

print("\nBlur Activation Map:")
print(blur_output)

Input Matrix:
[[10 20 30 40 50]
 [20 30 40 50 60]
 [30 40 50 60 70]
 [40 50 60 70 80]
 [50 60 70 80 90]]

Edge Detection Activation Map:
[[60. 60. 60.]
 [60. 60. 60.]
 [60. 60. 60.]]

Blur Activation Map:
[[30. 40. 50.]
 [40. 50. 60.]
 [50. 60. 70.]]


In [28]:
# 5.Pick any Instagram photo, convert it to grayscale and a small NumPy array (e.g., 8x8), and use your convolution function to apply a custom filter of your choice.
# Show the input and output arrays and briefly describe what feature your filter detects.

from PIL import Image
import numpy as np

image = Image.open("images.png")

gray_image = image.convert("L")

small_image = gray_image.resize((8, 8))

image_array = np.array(small_image)

custom_filter = np.array([
    [-1, -1, -1],
    [ 0,  0,  0],
    [ 1,  1,  1]
])


In [29]:
def convolution(input_matrix, kernel):

    rows, cols = input_matrix.shape
    k_rows, k_cols = kernel.shape

    output = np.zeros((
        rows - k_rows + 1,
        cols - k_cols + 1
    ))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):

            region = input_matrix[
                i:i+k_rows,
                j:j+k_cols
            ]

            output[i, j] = np.sum(region * kernel)

    return output

In [30]:
output = convolution(image_array, custom_filter)

print("8x8 Grayscale Input Array:")
print(image_array)

print("\nCustom Filter:")
print(custom_filter)

print("\nOutput Array:")
print(output)

8x8 Grayscale Input Array:
[[255 255 255 255 255 255 255 255]
 [255 255 255 251 251 255 255 255]
 [255 255 247 211 189 233 255 255]
 [255 246 164 152 167 187 250 255]
 [255 244 141 145 149 156 237 255]
 [255 255 196 125 169 185 251 255]
 [255 255 251 231 252 255 255 255]
 [255 255 255 255 255 255 255 255]]

Custom Filter:
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]

Output Array:
[[  -8.  -52. -118. -132.  -88.  -22.]
 [-100. -199. -274. -251. -157.  -73.]
 [-117. -183. -212. -183. -135.  -95.]
 [  41.   14.    7.  -27.    1.   -1.]
 [ 121.  207.  299.  288.  220.  117.]
 [  59.  189.  275.  286.  160.   74.]]
