In [3]:
# 1. Create a 6x6 NumPy array with random integers (0-255) to simulate a grayscale image, then apply a 2x2 max pooling operation with a
# stride of 2 and print the resulting reduced array.

import numpy as np

np.random.seed(10)
image = np.random.randint(0, 256, (6, 6))

print("Original 6x6 Image:")
print(image)

output = np.zeros((3, 3))

for i in range(0, 6, 2):
    for j in range(0, 6, 2):
        region = image[i:i+2, j:j+2]
        output[i//2, j//2] = np.max(region)

print("\nAfter 2x2 Max Pooling:")
print(output)

Original 6x6 Image:
[[  9 125 228  15  64 113]
 [123 156 217 221 240 157]
 [113 250   8  73   0 234]
 [ 40 246 164 115  16 100]
 [239 139  54  88 107 122]
 [ 62  33 200 100 206 177]]

After 2x2 Max Pooling:
[[156. 228. 240.]
 [250. 164. 234.]
 [239. 200. 206.]]


In [5]:
# 2.Write a Python function average_pooling_2x2(image) that takes a 2D NumPy array and returns a new
# array after applying 2x2 average pooling with stride 2.

import numpy as np

def average_pooling_2x2(image):

    rows, cols = image.shape

    output = np.zeros((rows // 2, cols // 2))

    for i in range(0, rows, 2):
        for j in range(0, cols, 2):

            region = image[i:i+2, j:j+2]

            output[i//2, j//2] = np.mean(region)

    return output


In [7]:
image = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

result = average_pooling_2x2(image)

print("Original Image:")
print(image)

print("\nAverage Pooled Image:")
print(result)

Original Image:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Average Pooled Image:
[[ 35.  55.]
 [115. 135.]]


In [9]:
# 3.Given a 4x4 feature map array, manually perform both max pooling and average pooling with a 2x2 window and stride 2, and compare the results side by side.<br><br><em><strong>Hint:</strong> Show both resulting arrays and explain 
# in one line which pooling method keeps more details from the original image.</em>

import numpy as np

feature_map = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

max_output = np.zeros((2, 2))
average_output = np.zeros((2, 2))

for i in range(0, 4, 2):
    for j in range(0, 4, 2):

        region = feature_map[i:i+2, j:j+2]

        max_output[i//2, j//2] = np.max(region)

        average_output[i//2, j//2] = np.mean(region)


In [11]:
print("Original Feature Map:")
print(feature_map)

print("\nMax Pooling:")
print(max_output)

print("\nAverage Pooling:")
print(average_output)

Original Feature Map:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Max Pooling:
[[ 6.  8.]
 [14. 16.]]

Average Pooling:
[[ 3.5  5.5]
 [11.5 13.5]]


In [14]:
# 4.Combine a single 3x3 convolution layer (use any simple filter, e.g., edge detection) followed by a 2x2 max pooling layer
# on a 5x5 input array. Show the output after each step.

import numpy as np

input_image = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 8, 9]
])

kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

conv_output = np.zeros((3, 3))

for i in range(3):
    for j in range(3):

        region = input_image[i:i+3, j:j+3]

        conv_output[i, j] = np.sum(region * kernel)

print("Input Image:")
print(input_image)

print("\nAfter Convolution:")
print(conv_output)

Input Image:
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]

After Convolution:
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [15]:
pool_output = np.zeros((1, 1))

for i in range(0, 2, 2):
    for j in range(0, 2, 2):

        region = conv_output[i:i+2, j:j+2]

        pool_output[i//2, j//2] = np.max(region)

print("\nAfter 2x2 Max Pooling:")
print(pool_output)


After 2x2 Max Pooling:
[[6.]]


In [ ]:
# 5.Explain in your own words, using an example from Instagram or Zomato, how pooling layers help reduce
# computation and improve feature extraction in deep learning models.

Pooling layers reduce the size of feature maps, which decreases the number of calculations required by later layers.