In [2]:
#1.Prepare a sequence dataset from Flipkart product prices over 10 days (you can create fake data) and reshape it into 
# the format required for LSTM input using NumPy.

import numpy as np

prices = np.array([999, 1049, 1099, 1079, 1149, 1199, 1249, 1229, 1299, 1349], dtype=float)

X = []
y = []

for i in range(len(prices) - 3):
    X.append(prices[i:i+3])
    y.append(prices[i+3])


X = np.array(X)
y = np.array(y)

X = X.reshape((X.shape[0], X.shape[1], 1))

print("Price sequence:", prices)
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X:")
print(X)
print("y:")
print(y)

Price sequence: [ 999. 1049. 1099. 1079. 1149. 1199. 1249. 1229. 1299. 1349.]
X shape: (7, 3, 1)
y shape: (7,)
X:
[[[ 999.]
  [1049.]
  [1099.]]

 [[1049.]
  [1099.]
  [1079.]]

 [[1099.]
  [1079.]
  [1149.]]

 [[1079.]
  [1149.]
  [1199.]]

 [[1149.]
  [1199.]
  [1249.]]

 [[1199.]
  [1249.]
  [1229.]]

 [[1249.]
  [1229.]
  [1299.]]]
y:
[1079. 1149. 1199. 1249. 1229. 1299. 1349.]


In [5]:
# 2.Build a simple LSTM model in Keras to predict the next value in your prepared Flipkart price sequence and train it for 10 epochs.

import numpy as np 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

prices = np.array([999, 1049, 1099, 1079, 1149, 1199, 1249, 1229, 1299, 1349], dtype=float)

X = []
y = []

for i in range(len(prices) - 3):
    X.append(prices[i:i+3])
    y.append(prices[i+3])


X = np.array(X)
y = np.array(y)

X = X.reshape((X.shape[0], X.shape[1], 1))

model = Sequential([LSTM(32, input_shape=(3,1)), Dense(1)]) 

model.compile(optimizer="adam", loss="mse")
history = model.fit(X, y, epochs=10, verbose=1) 

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1500751.8750
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1500573.2500
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1500504.8750
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1500448.8750
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 1500377.3750
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1500295.3750
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1500197.7500
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 1500073.7500
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1499945.8750
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1499851.6250


In [8]:
# 3.Evaluate your trained LSTM model by predicting the next price in the sequence, and print both the predicted and actual values for comparison.
# <br><br><em><strong>Hint:</strong> Use model.predict() and compare with the last actual value in your test set.</em>

last_sequence = np.array([1199, 1249, 1229], dtype=float)
last_sequence = last_sequence.reshape((1, 3, 1))

predicted_price = model.predict(last_sequence)

actual_price = 1299

print("Pridicted Price:", predicted_price[0][0])
print("Actual Price:", actual_price)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
Pridicted Price: 0.06683064
Actual Price: 1299


In [9]:
# 4. Write a short code snippet to switch your LSTM layer to a GRU layer in the same model and retrain it. 
# Compare the training time and prediction result with your LSTM model.<br><br><em><strong>Hint:</strong> Replace keras.layers.LSTM with keras.layers.GRU and keep other parameters the same.</em>

import time 
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense

gru_model = Sequential([GRU(32, input_shape=(3,1)), Dense(1)])
gru_model.compile(optimizer="adam", loss="mse")

start_time = time.time()
gru_history = gru_model.fit(X, y, epochs=10, verbose=1)

lstm_training_time = time.time() - start_time
gru_training_time = time.time() - start_time

gru_prediction = gru_model.predict(last_sequence)

print("LSTM Training Time:", lstm_training_time, "seconds")
print("GRU Training Time:", gru_training_time, "seconds")
print("LSTM Prediction:", predicted_price[0][0])
print("GRU Prediction:", gru_prediction[0][0])
print("Actual Price:", actual_price)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 1497928.8750
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1497711.7500
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 1497480.6250
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 1497369.3750
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1497329.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 1497298.7500
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 1497269.3750
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 1497240.1250
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1497210.7500
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 1497181.3750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step
LSTM Training Time: 2.3413233757019043 seconds
GRU Training Time: 2.3413617610931396 seconds
LSTM Prediction: 0.06683064
GRU Prediction: 1.1476558
Actual Price: 1299


In [59]:
# 5.Use ChatGPT to generate a Python function that prepares any sequence data (such as daily Spotify song play counts) for LSTM input, 
# and explain in your own words how the function works.

import numpy as np 

def prepare_lstm_data(sequence, time_steps=3):
    sequence = np.array(sequence, dtype=float)

    X = []
    y = []

    for i in range(len(sequence) - time_steps):
        X.append(sequence[i:i + time_steps])
        y.append(sequence[i + time_steps])

    X = np.array(X)
    y = np.array(y)

    X = X.reshape((X.shape[0], X.shape[1], 1))

    return X, y

spotify_plays = [120, 145, 160, 180, 175, 200, 220, 240]

X, y = prepare_lstm_data(spotify_plays, time_steps=3)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("X:")
print(X)
print("y:")
print(y)

X shape: (5, 3, 1)
y shape: (5,)
X:
[[[120.]
  [145.]
  [160.]]

 [[145.]
  [160.]
  [180.]]

 [[160.]
  [180.]
  [175.]]

 [[180.]
  [175.]
  [200.]]

 [[175.]
  [200.]
  [220.]]]
y:
[180. 175. 200. 220. 240.]
